# Generated by Django 5.0.7 on 2024-07-23 13:26

import django.db.models.deletion
import localflavor.in_.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address_line_1', models.CharField(max_length=170)),
                ('Address_line_2', models.CharField(max_length=170, null=True)),
                ('City', models.CharField(max_length=64)),
                ('State', localflavor.in_.models.INStateField(default='WB', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.location'),
        ),
    ]
